// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infra;

#nullable disable

namespace UrlShortener.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Models.UrlEncurtada", b =>
                {
                    b.Property<string>("UrlCurta")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("url_curta");

                    b.Property<long>("ContadorCliques")
                        .HasColumnType("bigint")
                        .HasColumnName("contador_cliques");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_original");

                    b.HasKey("UrlCurta");

                    b.HasIndex("UrlCurta")
                        .IsUnique();

                    b.ToTable("urls_encurtadas");
                });
#pragma warning restore 612, 618
        }
    }
}
